"""Write dbt models for MappingSpecs.

Two emission paths:

* **staging/** — single-source-table specs (M1). One `stg_<target>_from_<src>.sql`
  per (target, source-table) group:

      {{ config(materialized='view', tags=['m1', 'DimCustomer']) }}
      select
          <expr1>  as  <alias1>,  -- comments
          <expr2>  as  <alias2>,
      from {{ source('aw_oltp', 'Person_Person') }}

* **intermediate/** — multi-source-table specs (M2.2+). One
  `int_<target>_<spec>.sql` per multi-source spec, with an INNER JOIN derived from
  the FK relationship in the source profile:

      {{ config(materialized='view', tags=['m2', 'FactInternetSales']) }}
      select
          SalesOrderHeader.TaxAmt * SalesOrderDetail.LineTotal / SalesOrderHeader.SubTotal AS TaxAmt
      from {{ source('aw_oltp', 'Sales_SalesOrderHeader') }} as SalesOrderHeader
      inner join {{ source('aw_oltp', 'Sales_SalesOrderDetail') }} as SalesOrderDetail
          on SalesOrderDetail.SalesOrderID = SalesOrderHeader.SalesOrderID

  Specs whose tables aren't FK-linked (or that span 3+ tables) still fall through
  to the `_unmodeled_multi_source.txt` sidecar.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from dbt_emit._parsing import (
    intermediate_model_name,
    model_name,
    source_table_for,
    source_tables_for,
    split_select_expr,
    target_column_for,
    target_table_for,
)
from schemas import ColumnProfile, MappingSpec, SchemaProfile


def _format_comment(spec: MappingSpec) -> str:
    pr = f"{spec.validation_pass_rate:.2f}" if spec.validation_pass_rate is not None else "n/a"
    sources = ",".join(spec.source_fqns)
    return (
        f"-- pattern={spec.pattern.value}; source(s)={sources}; "
        f"llm_conf={spec.llm_confidence:.2f}; pass_rate={pr}"
    )


def _emit_one_model(
    target_schema: str,
    target_table: str,
    src_schema: str,
    src_table: str,
    specs: list[MappingSpec],
    *,
    run_id: str,
    source_name: str,
    out_dir: Path,
) -> Path:
    name = model_name(target_schema, target_table, src_schema, src_table)
    source_tbl = f"{src_schema}_{src_table}"

    select_lines: list[str] = []
    for i, spec in enumerate(specs):
        parsed = split_select_expr(spec.sql)
        if parsed is None:
            # Couldn't parse — emit as a commented block so dbt still parses the file.
            select_lines.append(f"    -- UNPARSEABLE SPEC for {spec.target_fqn}: {spec.sql!r}")
            continue
        expr, alias = parsed
        terminator = "," if i < len(specs) - 1 else ""
        select_lines.append(f"    {expr} AS {alias}{terminator}  {_format_comment(spec)}")

    body = "\n".join(select_lines) if select_lines else "    1 AS placeholder"

    sql = (
        f"{{{{ config(materialized='view', tags=['m1', {target_table!r}]) }}}}\n\n"
        f"-- Generated by Integration-Agent  run_id={run_id}\n"
        f"-- Target:   {target_schema}.{target_table}\n"
        f"-- Source:   {src_schema}.{src_table}\n\n"
        f"select\n"
        f"{body}\n"
        f"from {{{{ source({source_name!r}, {source_tbl!r}) }}}}\n"
    )

    models_dir = out_dir / "models" / "staging"
    models_dir.mkdir(parents=True, exist_ok=True)
    path = models_dir / f"{name}.sql"
    path.write_text(sql, encoding="utf-8")
    return path


def _columns_by_fqn(profile: SchemaProfile) -> dict[str, ColumnProfile]:
    return {c.fqn: c for tbl in profile.tables for c in tbl.columns}


def _find_fk_between(
    profile: SchemaProfile, table_a: tuple[str, str], table_b: tuple[str, str]
) -> tuple[tuple[str, str], str, tuple[str, str], str] | None:
    """Find an FK linking table_a + table_b. Returns (child_table, child_col, parent_table, parent_col).

    Mirrors validator.runner._find_fk_between, but returns oriented direction so callers
    know which side is the FK owner.
    """
    cols_by_fqn = _columns_by_fqn(profile)
    pair_a_str = f"{table_a[0]}.{table_a[1]}"
    pair_b_str = f"{table_b[0]}.{table_b[1]}"
    for col in cols_by_fqn.values():
        if not col.fk_ref:
            continue
        owner = (col.table_schema, col.table_name)
        ref_parts = col.fk_ref.rsplit(".", 1)
        if len(ref_parts) != 2:
            continue
        ref_table_str, ref_col = ref_parts
        if owner == table_a and ref_table_str == pair_b_str:
            return (table_a, col.column_name, table_b, ref_col)
        if owner == table_b and ref_table_str == pair_a_str:
            return (table_b, col.column_name, table_a, ref_col)
    return None


def _emit_intermediate_model(
    spec: MappingSpec,
    fk: tuple[tuple[str, str], str, tuple[str, str], str],
    *,
    run_id: str,
    source_name: str,
    out_dir: Path,
) -> Path:
    """Emit a single multi-source-spec dbt model with INNER JOIN."""
    child_tbl, child_col, parent_tbl, parent_col = fk
    tgt_schema, tgt_table = target_table_for(spec)
    tgt_col = target_column_for(spec)
    name = intermediate_model_name(tgt_table, tgt_col)

    parsed = split_select_expr(spec.sql)
    if parsed is None:
        select_line = f"    -- UNPARSEABLE SPEC for {spec.target_fqn}: {spec.sql!r}"
    else:
        expr, alias = parsed
        select_line = f"    {expr} AS {alias}  {_format_comment(spec)}"

    parent_alias = parent_tbl[1]
    child_alias = child_tbl[1]
    parent_source = f"{parent_tbl[0]}_{parent_tbl[1]}"
    child_source = f"{child_tbl[0]}_{child_tbl[1]}"

    sources_doc = ", ".join(f"{t[0]}.{t[1]}" for t in source_tables_for(spec))
    sql = (
        f"{{{{ config(materialized='view', tags=['m2', {tgt_table!r}]) }}}}\n\n"
        f"-- Generated by Integration-Agent  run_id={run_id}\n"
        f"-- Target:   {tgt_schema}.{tgt_table}.{tgt_col} (multi-source intermediate)\n"
        f"-- Sources:  {sources_doc}\n"
        f"-- JOIN:     {child_alias}.{child_col} = {parent_alias}.{parent_col}\n\n"
        f"select\n"
        f"{select_line}\n"
        f"from {{{{ source({source_name!r}, {parent_source!r}) }}}} as {parent_alias}\n"
        f"inner join {{{{ source({source_name!r}, {child_source!r}) }}}} as {child_alias}\n"
        f"    on {child_alias}.{child_col} = {parent_alias}.{parent_col}\n"
    )

    models_dir = out_dir / "models" / "intermediate"
    models_dir.mkdir(parents=True, exist_ok=True)
    path = models_dir / f"{name}.sql"
    path.write_text(sql, encoding="utf-8")
    return path


def write_models(
    specs: list[MappingSpec],
    out_dir: Path,
    *,
    run_id: str = "w4b",
    source_name: str = "aw_oltp",
    source_profile: SchemaProfile | None = None,
) -> list[Path]:
    """Group specs by (target_table, source_table) and emit one .sql per group.

    Multi-source-table specs are emitted as `models/intermediate/int_*.sql` JOIN
    models when the source_profile has a discoverable FK linking them; otherwise
    they fall through to the _unmodeled_multi_source.txt sidecar (3+ tables, missing
    FK, or no source_profile).

    Returns the list of written paths.
    """
    groups: dict[tuple[str, str, str, str], list[MappingSpec]] = defaultdict(list)
    multi_source: list[MappingSpec] = []
    for spec in specs:
        src = source_table_for(spec)
        if src is None:
            multi_source.append(spec)
            continue
        tgt_schema, tgt_table = target_table_for(spec)
        groups[(tgt_schema, tgt_table, src[0], src[1])].append(spec)

    written: list[Path] = []
    for (tgt_schema, tgt_table, src_schema, src_table), group_specs in sorted(groups.items()):
        path = _emit_one_model(
            tgt_schema,
            tgt_table,
            src_schema,
            src_table,
            group_specs,
            run_id=run_id,
            source_name=source_name,
            out_dir=out_dir,
        )
        written.append(path)

    skipped: list[MappingSpec] = []
    for spec in multi_source:
        spec_tables = sorted(source_tables_for(spec))
        if source_profile is not None and len(spec_tables) == 2:
            fk = _find_fk_between(source_profile, spec_tables[0], spec_tables[1])
            if fk is not None:
                path = _emit_intermediate_model(
                    spec, fk, run_id=run_id, source_name=source_name, out_dir=out_dir
                )
                written.append(path)
                continue
        skipped.append(spec)

    if skipped:
        sidecar = out_dir / "models" / "staging" / "_unmodeled_multi_source.txt"
        sidecar.parent.mkdir(parents=True, exist_ok=True)
        sidecar.write_text(
            "Specs with no FK-discoverable JOIN (or 3+ source tables) — deferred:\n"
            + "\n".join(f"  {s.target_fqn} (sources: {s.source_fqns})" for s in skipped),
            encoding="utf-8",
        )
        written.append(sidecar)

    return written
