"""Write one stg_<target_table>_from_<source_table>.sql per (target, source-table) group.

Each emitted file looks roughly like:

    {{ config(materialized='view', tags=['m1', 'DimCustomer']) }}

    -- Generated by Integration-Agent  run_id=<id>
    -- Target:   dbo.DimCustomer
    -- Source:   Person.Person

    select
        <expr1>  as  <alias1>,  -- pattern=rename; source=Person.Person.FirstName; llm_conf=0.98; pass_rate=1.00
        <expr2>  as  <alias2>,  -- ...
        ...
    from {{ source('aw_oltp', 'Person_Person') }}

Grouping rule:
    group_key = (target_schema, target_table, source_schema, source_table)
    where source_table is the SINGLE source table of each spec. Multi-source-table
    specs are collected into a separate file that includes a TODO comment instead
    of a real FROM, so dbt parse is deferred until the user adds JOIN logic. This
    matches the validator's single-table-only M1 scope.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from dbt_emit._parsing import (
    model_name,
    source_table_for,
    split_select_expr,
    target_table_for,
)
from schemas import MappingSpec


def _format_comment(spec: MappingSpec) -> str:
    pr = f"{spec.validation_pass_rate:.2f}" if spec.validation_pass_rate is not None else "n/a"
    sources = ",".join(spec.source_fqns)
    return (
        f"-- pattern={spec.pattern.value}; source(s)={sources}; "
        f"llm_conf={spec.llm_confidence:.2f}; pass_rate={pr}"
    )


def _emit_one_model(
    target_schema: str,
    target_table: str,
    src_schema: str,
    src_table: str,
    specs: list[MappingSpec],
    *,
    run_id: str,
    source_name: str,
    out_dir: Path,
) -> Path:
    name = model_name(target_schema, target_table, src_schema, src_table)
    source_tbl = f"{src_schema}_{src_table}"

    select_lines: list[str] = []
    for i, spec in enumerate(specs):
        parsed = split_select_expr(spec.sql)
        if parsed is None:
            # Couldn't parse — emit as a commented block so dbt still parses the file.
            select_lines.append(f"    -- UNPARSEABLE SPEC for {spec.target_fqn}: {spec.sql!r}")
            continue
        expr, alias = parsed
        terminator = "," if i < len(specs) - 1 else ""
        select_lines.append(f"    {expr} AS {alias}{terminator}  {_format_comment(spec)}")

    body = "\n".join(select_lines) if select_lines else "    1 AS placeholder"

    sql = (
        f"{{{{ config(materialized='view', tags=['m1', {target_table!r}]) }}}}\n\n"
        f"-- Generated by Integration-Agent  run_id={run_id}\n"
        f"-- Target:   {target_schema}.{target_table}\n"
        f"-- Source:   {src_schema}.{src_table}\n\n"
        f"select\n"
        f"{body}\n"
        f"from {{{{ source({source_name!r}, {source_tbl!r}) }}}}\n"
    )

    models_dir = out_dir / "models" / "staging"
    models_dir.mkdir(parents=True, exist_ok=True)
    path = models_dir / f"{name}.sql"
    path.write_text(sql, encoding="utf-8")
    return path


def write_models(
    specs: list[MappingSpec],
    out_dir: Path,
    *,
    run_id: str = "w4b",
    source_name: str = "aw_oltp",
) -> list[Path]:
    """Group specs by (target_table, source_table) and emit one .sql per group.

    Returns the list of written paths.
    """
    groups: dict[tuple[str, str, str, str], list[MappingSpec]] = defaultdict(list)
    skipped: list[MappingSpec] = []
    for spec in specs:
        src = source_table_for(spec)
        if src is None:
            skipped.append(spec)
            continue
        tgt_schema, tgt_table = target_table_for(spec)
        groups[(tgt_schema, tgt_table, src[0], src[1])].append(spec)

    written: list[Path] = []
    for (tgt_schema, tgt_table, src_schema, src_table), group_specs in sorted(groups.items()):
        path = _emit_one_model(
            tgt_schema,
            tgt_table,
            src_schema,
            src_table,
            group_specs,
            run_id=run_id,
            source_name=source_name,
            out_dir=out_dir,
        )
        written.append(path)

    if skipped:
        # Write a sidecar listing so the eval harness knows these weren't modeled.
        sidecar = out_dir / "models" / "staging" / "_unmodeled_multi_source.txt"
        sidecar.parent.mkdir(parents=True, exist_ok=True)
        sidecar.write_text(
            "Specs with >1 source table — deferred to M2 for JOIN-capable modeling:\n"
            + "\n".join(f"  {s.target_fqn} (sources: {s.source_fqns})" for s in skipped),
            encoding="utf-8",
        )
        written.append(sidecar)

    return written
