"""Write models/staging/schema.yml with sources + per-model column tests."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import yaml

from dbt_emit._parsing import (
    model_name,
    source_table_for,
    split_select_expr,
    target_table_for,
)
from schemas import MappingSpec


def _tests_for_spec(spec: MappingSpec) -> list[object]:
    """Render MappingSpec.tests as dbt-compatible YAML items."""
    out: list[object] = []
    for t in spec.tests:
        if t.config:
            # dbt 1.10+ requires generic-test args nested under `arguments:` (was top-level pre-1.10).
            out.append({t.name: {"arguments": dict(t.config)}})
        else:
            out.append(t.name)
    return out


def _parsed_alias(spec: MappingSpec) -> str | None:
    parsed = split_select_expr(spec.sql)
    return parsed[1] if parsed else None


def write_schema_yml(
    specs: list[MappingSpec],
    out_dir: Path,
    *,
    source_name: str = "aw_oltp",
    source_schema: str = "source_raw",
) -> Path:
    """Write `models/staging/schema.yml` summarizing sources + models+tests."""
    # Collect unique source tables across all modeled specs
    source_tables: set[tuple[str, str]] = set()
    # Group specs by (target, source) the same way model.py does
    groups: dict[tuple[str, str, str, str], list[MappingSpec]] = defaultdict(list)
    for spec in specs:
        src = source_table_for(spec)
        if src is None:
            continue
        tgt = target_table_for(spec)
        source_tables.add(src)
        groups[(tgt[0], tgt[1], src[0], src[1])].append(spec)

    sources_block = [
        {
            "name": source_name,
            "schema": source_schema,
            "tables": sorted(
                [{"name": f"{s}_{t}"} for s, t in source_tables], key=lambda d: d["name"]
            ),
        }
    ]

    models_block: list[dict] = []
    for (tgt_schema, tgt_table, src_schema, src_table), group_specs in sorted(groups.items()):
        columns: list[dict] = []
        for spec in group_specs:
            alias = _parsed_alias(spec)
            if alias is None:
                continue
            col_entry: dict = {"name": alias}
            tests = _tests_for_spec(spec)
            if tests:
                col_entry["tests"] = tests
            columns.append(col_entry)
        models_block.append(
            {
                "name": model_name(tgt_schema, tgt_table, src_schema, src_table),
                "description": (
                    f"Staging model for {tgt_schema}.{tgt_table}, generated by "
                    f"Integration-Agent from source {src_schema}.{src_table}."
                ),
                "columns": columns,
            }
        )

    payload = {"version": 2, "sources": sources_block, "models": models_block}

    out_path = out_dir / "models" / "staging" / "schema.yml"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        yaml.safe_dump(payload, sort_keys=False, default_flow_style=False),
        encoding="utf-8",
    )
    return out_path


__all__ = ["write_schema_yml"]
